// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package api

type CommandResult struct {
	Error *string `json:"error,omitempty"`
}

type Document struct {
	ID     *string   `json:"id,omitempty"`
	Text   *string   `json:"text,omitempty"`
	Source *string   `json:"source,omitempty"`
	Vector []float64 `json:"vector,omitempty"`
	Meta   *string   `json:"meta,omitempty"`
}

type DocumentInput struct {
	ID     *string   `json:"id,omitempty"`
	Text   *string   `json:"text,omitempty"`
	Source *string   `json:"source,omitempty"`
	Vector []float64 `json:"vector,omitempty"`
	Meta   *string   `json:"meta,omitempty"`
}

type Mutation struct {
}

type PingResult struct {
	Pong string `json:"pong"`
}

type Query struct {
}

type QueryInput struct {
	Query string `json:"query"`
}

type SearchResult struct {
	Results    []*Document `json:"results"`
	TotalCount int         `json:"totalCount"`
	Error      *string     `json:"error,omitempty"`
}

type StatsResult struct {
	NumDocuments int `json:"numDocuments"`
}
