name: Sanity Checks

on:
  pull_request:
    branches:
    - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Build
      run: go build ./...

    - name: Format (gofmt)
      run: |
        fmt_out=$(gofmt -l .)
        if [ -n "$fmt_out" ]; then
          echo "The following files are not properly formatted:" >&2
          echo "$fmt_out" >&2
          exit 1
        fi

    - name: Vet
      run: go vet ./...

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Staticcheck
      run: ~/go/bin/staticcheck ./...

    - name: Test
      run: go test -v ./...
